### ISSUE TITLE
Allow user to vote on images

### ISSUE THREAD

**Issue by JohnWarren1** [BruvaJ/djangoBootstrapExperiment1#2]

**Comment by BruvaJ** [comment]
Must prevent users from voting more than once. 

Rather than requiring a login would rather do this with a cookie or database entry:

**cookie**
https://stackoverflow.com/questions/11059191/django-guests-vote-only-once-poll
probably best solution. Risk is pretty low.

**database** (may have scaling issues. Seems a nice solution though)
a table that logs:
- ip
- image id
- vote type? 
.... depends whether this table stores vote result or just ips that have voted. Could be flushed daily.

**Comment by JohnWarren1** [comment]
**Alternative:**
http://beaverbird.com/

**Comment by JohnWarren1** [comment]
done
